# Generated by Django 2.1.1 on 2020-03-30 01:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('zipcode', models.CharField(max_length=20)),
                ('firstbuyersonly', models.CharField(max_length=100)),
                ('ataglance', models.CharField(max_length=100)),
                ('canbecombined', models.CharField(max_length=100)),
                ('requiresinspection', models.CharField(max_length=100)),
                ('mustbeprimary', models.CharField(max_length=100)),
                ('creditrequirment', models.CharField(max_length=100)),
                ('employerparticipation', models.CharField(max_length=100)),
                ('maxdebtotincome', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('Neighborhoods', models.TextField(blank=True)),
                ('amount', models.IntegerField(blank=True)),
                ('minimumcontribution', models.IntegerField(blank=True)),
                ('mortgageamount', models.IntegerField(blank=True)),
                ('amountofassistance', models.IntegerField(blank=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lenders.Lender')),
            ],
        ),
    ]
