# Generated by Django 2.1.1 on 2020-04-13 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchsave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100)),
                ('link_visited', models.CharField(blank=True, max_length=100)),
                ('misc', models.CharField(blank=True, max_length=100)),
                ('length', models.IntegerField(blank=True)),
                ('time_visited', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
