# Generated by Django 2.1.1 on 2020-04-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_searchsave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchsave',
            name='link_visited',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
