# Generated by Django 2.1.1 on 2020-04-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200417_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ami',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='canbecombinedwith',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='listing',
            name='participatinglenders',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='listing',
            name='programcontact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='programdistribution',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
