# Generated by Django 2.1.1 on 2020-04-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_blocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main',
        ),
        migrations.AddField(
            model_name='listing',
            name='amilimit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='eligibilitylimitations',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='listing',
            name='eligible',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='listing',
            name='fixedratemortgagesonly',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='getstarted',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='householdincomerestrictions',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='mustearncounselingcertificate',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
