# Generated by Django 2.1.1 on 2020-04-17 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200417_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='program',
            new_name='programtype',
        ),
    ]
