# Generated by Django 2.1.1 on 2020-04-17 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20200417_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='programname',
        ),
    ]
