# Generated by Django 2.1.1 on 2020-04-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20200417_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='lender',
        ),
        migrations.AddField(
            model_name='listing',
            name='programoriginator',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
