# Generated by Django 2.1.1 on 2020-04-18 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20200417_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='list_date',
        ),
    ]
