# Generated by Django 2.1.1 on 2020-04-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_remove_listing_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='fixedratemortgagesonly',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='householdincomerestrictions',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='mustearncounselingcertificate',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
