# Generated by Django 2.1.1 on 2020-04-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20200418_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='amountofassistance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='getstarted',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='minimumcontribution',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='mortgageamount',
            field=models.IntegerField(null=True),
        ),
    ]
