# Generated by Django 2.1.1 on 2020-04-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20200418_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='canbecombinedwith',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='participatinglenders',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
