# Generated by Django 2.1.1 on 2020-04-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_auto_20200418_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='programdistribution',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='programname',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
