# Generated by Django 2.1.1 on 2020-05-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20200418_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterField(
            model_name='listing',
            name='ami',
            field=models.IntegerField(blank=True, null=True, verbose_name='AMI'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='amilimit',
            field=models.TextField(blank=True, null=True, verbose_name='AMI Limit'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='amountofassistance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Amount of Asistance'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ataglance',
            field=models.CharField(blank=True, max_length=100, verbose_name='At a glance'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='canbecombined',
            field=models.CharField(blank=True, max_length=100, verbose_name='Can be combined?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='canbecombinedwith',
            field=models.CharField(blank=True, max_length=400, verbose_name='Can be combined with'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='creditrequirment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Credit Requirement'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='eligibilitylimitations',
            field=models.TextField(blank=True, max_length=400, verbose_name='Eligibility Limitations'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='employerparticipation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Employer Participation'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='firstbuyersonly',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Time Buyers Only?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='fixedratemortgagesonly',
            field=models.TextField(blank=True, max_length=50, verbose_name='Fixed Rate Mortages Only?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='getstarted',
            field=models.TextField(blank=True, max_length=500, verbose_name='Get Started'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='householdincomerestrictions',
            field=models.TextField(blank=True, max_length=50, verbose_name='Household Income Restrictions'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='maxdebtotincome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Max Debt to Income Ratio'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='minimumcontribution',
            field=models.IntegerField(null=True, verbose_name='Minimum Contribution'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='mortgageamount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mortgage Amount'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='mustbeprimary',
            field=models.CharField(blank=True, max_length=100, verbose_name='Must be primay residence?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='mustearncounselingcertificate',
            field=models.TextField(blank=True, max_length=50, verbose_name='Must earn Counseling Certificate?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='participatinglenders',
            field=models.CharField(blank=True, max_length=400, verbose_name='Participating Lender'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='programcontact',
            field=models.CharField(blank=True, max_length=400, verbose_name='Program Contact'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='programdistribution',
            field=models.CharField(blank=True, max_length=400, verbose_name='Program Distribution'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='programname',
            field=models.CharField(blank=True, max_length=400, verbose_name='Program Name'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='programoriginator',
            field=models.TextField(blank=True, max_length=400, verbose_name='Program Originator'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='programtype',
            field=models.CharField(blank=True, max_length=500, verbose_name='Program Type'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='requiresinspection',
            field=models.CharField(blank=True, max_length=100, verbose_name='Requires Inspection?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(blank=True, max_length=300, verbose_name='Zip Code'),
        ),
    ]
