# Generated by Django 2.1.1 on 2020-05-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Employer'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='familysize',
            field=models.CharField(blank=True, max_length=200, verbose_name='Family Size'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firsttimebuyer',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Time Home Buyer?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='householdincome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Annual Income'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.TextField(blank=True, max_length=200, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='veteran',
            field=models.CharField(blank=True, max_length=100, verbose_name='Veteran?'),
        ),
    ]
