# Generated by Django 2.1.1 on 2020-03-30 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('programdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('location', models.TextField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('is_mvp', models.BooleanField(default=False)),
            ],
        ),
    ]
